#!/bin/sh

set -e

# install alternatives links

if [ "$1" = "configure" ]; then
	update-alternatives --install /usr/bin/x-terminal-emulator \
	x-terminal-emulator /usr/bin/lilyterm 70
fi

#DEBHELPER#

exit 0

